apiVersion: apps/v1
kind: Deployment
metadata: 
  name: secrets-deployment
  labels:
    app: secrets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
    spec:
      containers:
      - name: secrets
        image: alxn787/backend-pg:8
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: env-file
          readOnly: true
          mountPath: "/app/secret"
      volumes:
      - name: env-file
        secret:
          secretName: backend-secret